agent_definitions:
  qlearning:
    type: qlearning
    hidden_layer_size: 60
    n_hidden_layers: 1
    gamma: 0.99
  dqn-30:
    type: DQN
    hidden_layer_size: 30
    n_hidden_layers: 1
    gamma: 0.99
    device: cpu
    sync_frequency: 100
    buffer_size: 1000
    sample_size: 100
  dqn-60:
    type: DQN
    hidden_layer_size: 60
    n_hidden_layers: 1
    gamma: 0.99
    device: cpu
    sync_frequency: 100
    buffer_size: 1000
    sample_size: 100
1agent_obst:
  map_image: maps/test_4x4.jpg
  agents:
    dqn-30: 1
  obstacles: 1
  epsilon_decay_length: 10000 # 1e4
  epsilon_start: 1.0
  epsilon_final: 0.01
  evolution_frequency: 0
  steps: 30000 # 3e4
  load_model: ''
  comment: ''
1agent_obst_9:
  map_image: maps/test_9x9.jpg
  agents:
    dqn-30: 1
  obstacles: 1
  epsilon_decay_length: 10000 # 1e4
  epsilon_start: 1.0
  epsilon_final: 0.0
  evolution_frequency: 0
  steps: 20000 # 2e4
  load_model: ''
  comment: ''
3agent_obst:
  map_image: maps/empty_4x4.jpg
  agents:
    dqn-30: 3
  obstacles: 2
  epsilon_decay_length: 40000 # 4e4
  epsilon_start: 0.5
  epsilon_final: 0.0
  evolution_frequency: 0
  steps: 100000 # 1e5
  load_model: '3agent'
  comment: ''
3agent_6:
  map_image: maps/test_6x6.jpg
  agents:
    dqn-30: 3
  obstacles: 0
  epsilon_decay_length: 40000 # 4e4
  epsilon_start: 0.5
  epsilon_final: 0.0
  evolution_frequency: 0
  steps: 100000 # 1e5
  load_model: '3agent_obst'
  comment: ''
3agent_9:
  map_image: maps/test_9x9.jpg
  agents:
    dqn-30: 3
  obstacles: 0
  epsilon_decay_length: 10000 # 1e4
  epsilon_start: 0.5
  epsilon_final: 0.0
  evolution_frequency: 1000
  steps: 10000 # 1e4
  load_model: '3agent_6'
  comment: ''
5agent-stage1:
  map_image: maps/test_9x9.jpg
  agents:
    - type: dqn-60
      n_agents: 5
      policy: basic_policy
  obstacles: 0
  epsilon_decay_length: 10000 # 1e4
  epsilon_start: 0.3
  epsilon_final: 0.1 # no 0 epsilon with deterministic policy
  goal_closeness: 5
  evolution_frequency: 1000 # evolution only in case some agents diverge
  steps: 10000 # 1e4
  comment: ''
5agent-stage2:
  map_image: maps/test_9x9.jpg
  agents:
    - type: dqn-60
      n_agents: 5
      load: 5agent-stage1/dqn-60
  obstacles: 0
  epsilon_decay_length: 10000 # 1e4
  epsilon_start: 0.5
  epsilon_final: 0.0
  goal_closeness: 5
  evolution_frequency: 1000 # 1e3
  steps: 10000 # 1e4
  comment: ''
