1agent:
  map_image: maps/test_3x3.jpg
  agents:
  - type: qlearning
    hidden_layer_size: 30
    n_hidden_layers: 1
    gamma: 0.9
  epsilon_decay_length: 200000 # 2e5
  epsilon_start: 1.0
  epsilon_final: 0.0
  steps: 300000 # 3e5
  load_model: ''
  comment: ''
1agent-dqn:
  map_image: maps/test_3x3.jpg
  agents:
  - type: DQN
    hidden_layer_size: 30
    n_hidden_layers: 1
    gamma: 0.9
    device: cpu
    sync_frequency: 1000
    buffer_size: 1000
    sample_size: 100
  epsilon_decay_length: 20000 # 2e4
  epsilon_start: 1.0
  epsilon_final: 0.0
  steps: 30000 # 3e4
  load_model: ''
  comment: ''
2agent:
  agents:
  - type: qlearning
    hidden_layer_size: 30
    n_hidden_layers: 1
    gamma: 0.9
  - type: qlearning
    hidden_layer_size: 30
    n_hidden_layers: 1
    gamma: 0.9
  comment: ''
  epsilon_decay_length: 400000 # 4e5
  epsilon_final: 0.0
  epsilon_start: 1.0
  hidden_layer_size: 40
  load_model: ''
  map_image: maps/test_3x3.jpg
  n_hidden_layers: 1
  steps: 600000 # 6e5
2agent-dqn:
  agents:
  - type: DQN
    hidden_layer_size: 30
    n_hidden_layers: 1
    gamma: 0.9
    device: cpu
    sync_frequency: 1000
    buffer_size: 1000
    sample_size: 100
  - type: DQN
    hidden_layer_size: 30
    n_hidden_layers: 1
    gamma: 0.9
    device: cpu
    sync_frequency: 1000
    buffer_size: 1000
    sample_size: 100
  comment: ''
  epsilon_decay_length: 20000 #2e4
  epsilon_final: 0.0
  epsilon_start: 1.0
  hidden_layer_size: 40
  load_model: ''
  map_image: maps/test_3x3.jpg
  n_hidden_layers: 1
  steps: 100000 # 1e5
