agent_definitions:
  dqn-60:
    type: DQN
    hidden_layer_size: 60
    n_hidden_layers: 1
    gamma: 0.99
    device: cpu
    sync_frequency: 100
    buffer_size: 1000
    sample_size: 100
  dqn-30:
    type: DQN
    hidden_layer_size: 30
    n_hidden_layers: 1
    gamma: 0.99
    device: cpu
    sync_frequency: 100
    buffer_size: 1000
    sample_size: 100
  dqn-30-2:
    type: DQN
    hidden_layer_size: 30
    n_hidden_layers: 1
    gamma: 0.99
    device: cpu
    sync_frequency: 100
    buffer_size: 10000
    sample_size: 1000
1agent:
  map_image: maps/test_4x4.jpg
  agents:
    dqn-30: 1
  epsilon_decay_length: 10000 # 1e4
  epsilon_start: 1.0
  epsilon_final: 0.0
  goal_closeness_decay_length: 5000
  goal_closeness_start: 1
  goal_closeness_final: 8
  steps: 20000 # 2e4
  load_model: ''
  comment: ''
2agent:
  map_image: maps/test_4x4.jpg
  agents:
    dqn-30: 2
  epsilon_decay_length: 40000 # 4e4
  epsilon_start: 1.0
  epsilon_final: 0.0
  goal_closeness_decay_length: 20000 # 2e4
  goal_closeness_start: 1
  goal_closeness_final: 7
  steps: 100000 # 1e5
  load_model: ''
  comment: ''
2agent-2:
  map_image: maps/test_4x4.jpg
  agents:
    dqn-30-2: 2
  epsilon_decay_length: 40000 # 4e4
  epsilon_start: 1.0
  epsilon_final: 0.0
  goal_closeness_decay_length: 20000 # 2e4
  goal_closeness_start: 1
  goal_closeness_final: 7
  steps: 100000 # 1e5
  load_model: ''
  comment: ''
